version: 0.0.4.{build}
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  verbosity: minimal
  publish_nuget: true
after_build:
  - nunit3-console "Tests\\bin\\Debug\\Tests.dll"
test: off
nuget:
  project_feed: true
deploy:
  provider: NuGet
  api_key:
    secure: tqiGBmod5X4QAhyd+yCL/+RqAOVouFERgnOQU8Ln2ayL+0C6usRgACow6EsUN7Gw
  artifact: /.*\.nupkg/
  on:
    branch: master
    appveyor_repo_tag: true
