version: 0.0.1.{build}
assembly_info:
  patch: true
  file: '**\\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  verbosity: minimal
after_build:
  - nunit3-console "Tests\\bin\\Debug\\Tests.dll" -nodots
test: off
